name: CoreWar - CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1
    - name: Loading tests
      run:  sudo apt update && sudo apt install build-essential

    - name: Test 1 -> asm build
      run:  cd asm && make
    - name: Test 2 -> vm build
      run:  cd corewar && make
    - name: Test 3 -> asm in advanced build
      run:  cd asm && gcc -o test src/*.o -I./include -g3 -Wall -Werror
    - name: Test 4 -> vm in advanced build
      run:  cd corewar && gcc -o test lib/*.o src/*.o bonus/*.o -I./include -g3 -Wall -Werror
    - name: Test 5 -> asm binary without arguments
      run: cd asm && ./asm
    - name: Test 6 -> vm binary without arguments
      run: cd corewar && ./corewar
